### ISSUE TITLE
plural support ?

### ISSUE THREAD

**Issue by johaven** [robisim74/angular-l10n#102]
Sorry, i tried to find an example for plural syntax in documentation but without success.
Is there no method to translate 'task' or 'tasks' according to numbers as below ?

```html
<li class="header">{{ 'user_tasks' | translate:lang:{nb_active: activeTasks, nb: tasks.length - activeTasks} }}</li>
```

**Comment by robisim74** [comment]
Apply to the arguments the pipes you need as in this snippet: https://github.com/robisim74/angular-l10n/wiki/Snippets#1

Otherwise, the numbers at the beginning of the keys are translated by default: here a cascading example with _i18nPlural_ Angular pipe: https://github.com/robisim74/angular-l10n-sample/blob/master/src/app/i18n/i18n.component.html#L29

**Comment by robisim74** [comment]
I'm closing this issue. If you need reopen it. Greetings

**Comment by johaven** [comment]
A simple example in documentation should be great.
With a simple example:
```javascript
{{(group.members.length > 1 ? 'members':'member') | translate:lang}}
```
