### ISSUE TITLE
Adding multiple providers and overriding duplicate keys

### ISSUE THREAD

**Issue by GenZodd** [robisim74/angular-l10n#103]
I have just started plugging in this model and so far very impressed. Nice work, even on the documentation. 

I found this capability for adding [multiple providers](https://github.com/robisim74/angular-l10n/blob/master/doc/spec.md#242-asynchronous-loading-of-json-files). However, I can't seem to figure out how overriding works if the same key is found in both providers. It always uses the same one regardless of the order I add them in. Does it handle overriding like this? 

```
this.translation.addConfiguration()
   .addProvider('../../assets/translation/locale-')
   .addProvider('../../assets/translation/security/locale-');
```

In translation folder, I have this. 
`
{
    "LoginWelcome": "Welcome"
}
`
In translation folder, I have this. 
`
{
    "LoginWelcome": "Welcome to security"
}
`
I was guessing that whatever one was added last would win but it is always showing "Welcome".

**Comment by robisim74** [comment]
Please, can you provide a plunker? http://embed.plnkr.co/UdKFunQFnD3TOkXp2v06/

**Comment by GenZodd** [comment]
Sure. You can find it here. https://plnkr.co/edit/INOtpdJZoIZRe7fKafmU

Thought this might be an easy answer. In the plunker I used your template. I then added a security folder under assets and added locale file with the same key of "change".

Then I updated the model.ts to add two providers.

```
this.translation.addConfiguration()
        .addProvider('./assets/locale-')
        .addProvider('./assets/security/locale-');
```

Plunker helped flush out the issue a little for me but seems there is still a bug? 

1) My main issue was I was adding the "root" locale file in the app module and then again in the security module. I did not think that would matter as they are not shared. As soon as I take the addProvider line out of the app module things work as I was expecting with the last added provider winning. If I add at the app.module level the app.module always wins. 

In plunker just click on the "security" link and that will take you to the security submodule and login components. Notice the text under the buttons. 

app module has `TranslationModule.forRoot()` and security model has `TranslationModule.forChild()`

2) The other thing I noticed in plunker is if I added `    .addProvider('./assets/security/locale-') ` to the app.module setup (so I have both) and the I start clicking the different languages the translations are not always the same. Somes times it gets the security translation and sometimes it gets the one in the asset root.

**Comment by robisim74** [comment]
The problem is that you are not using a _lazy loaded_ module: so you should not call the `forChild` method and not add a new configuration: if I remove them, everything works as expected:

![image](https://user-images.githubusercontent.com/14012361/27201657-c26bec0e-521e-11e7-8715-40b9310d64de.png)

See the Angular documentation: https://angular.io/guide/ngmodule#lazy-loading-modules-with-the-router and then the docs of this library: https://github.com/robisim74/angular-l10n/blob/master/doc/spec.md#5

However keep in mind that the order of providers does not guarantee that the data will be merged in the same order: for each request is made an _Http get_ asynchronous request, and the fact that they are usually executed in order is only because Javascript is not really asynchronous but single thread, and the files end in queue.

Performing asynchronous requests is the expected behavior for this library, because it would not make sense to wait sequentially to load the files.

**Comment by GenZodd** [comment]
Thanks @robisim74 it all makes sense now. I should have realized about lazy loading the module. Thanks for the help!
