### ISSUE TITLE
Usage questions

### ISSUE THREAD

**Issue by ili** [robisim74/angular-l10n#104]
**I'm submitting a...**
```
[ ] bug report
[ ] feature request
[x] support request
```

1.  What does `addLanguages` method for? If I do not call it translation works anyway.
1. What is the difference between `defineDefaultLocale` & `setDefaultLocale`? You see, when i'm calling `.defineDefaultLocale('en', 'US')` I do expect that English translation would be used regardless of my browser culture, but Russian is used (this is my browser's culture). If I do `setDefaultLocale('en', 'US')` everything working as i'm expecting.  So what would be your recommendations for the scenario: if user sets language in his profile use it in other case use browser's language.
1. Using directives - am I right that if I want to translate attribute (`l10n-attribute`) I should always use `l10nTranslate`?

**Comment by robisim74** [comment]
1) `addLanguages ` allows the system to know the languages used in the app: for example, the browser language is used only if it has been added; or to know the direction of language, or even simply to return available languages for selection.
2) `defineDefaultLocale` is used at the bootstrap only the first time the user starts the app, `setDefaultLocale` at runtime. `defineDefaultLocale` does not consider the language of the browser (unlike `defineDefaultLanguage`) because not all browsers return the whole locale. It is not even used if a choice has already been made, because it is stored, in a cookie, in LocalStorage etc, depending on the configuration. Try cleaning the cookies to see it run the first time.
`setDefaultLocale` forces the system to use the set locale, and saves it in the cookie.
3) Yes, you need to add the _master_ directive: `l10nTranslate` or `l10nDate` etc.

**Comment by ili** [comment]
@robisim74 thanks a lot!
