### ISSUE TITLE
Application-wide services in lazy-loaded modules

### ISSUE THREAD

**Issue by csentis** [robisim74/angular-l10n#130]
**I'm submitting a...**
```
[ ] bug report
[ ] feature request
[x] support request
```
Hi Roberto,

unfortunately, I have to be a little more detailed:

I have an `app.module.ts` with advanced configuration and direct loading. It contains, among others:

**app.module.ts**
```
import { LocalizationModule, TranslationService, L10nConfig, L10nLoader, ProviderType, StorageStrategy } from 'angular-l10n';

import { AppEN, AppDE } from './core/locales';

[...]

const appL10nConfig: L10nConfig = {
    locale: {
        languages: [
            { code: 'en', dir: 'ltr' },
            { code: 'de', dir: 'ltr' }
        ],
        defaultLocale: { languageCode: 'en', countryCode: 'US' },
        currency: 'EUR',
        // TODO: timezone: ,
        storage: StorageStrategy.Local,
        cookieExpiration: 30
    },
    translation: {
        translationData: [
            { languageCode: 'de', data: AppDE },
            { languageCode: 'en', data: AppEN }
        ],
        caching: true,
        composedKeySeparator: '.',
        missingKey: 'No translation key',
        missingValue: 'No translation value'
    }
};

// Advanced initialization.
export function initL10n(l10nLoader: L10nLoader): Function {
    return () => l10nLoader.load();
}

@NgModule({
    imports: [
        [...]
        LocalizationModule.forRoot(appL10nConfig), // New instance of LocalizationService
        [...]
    ],
    [...]
    providers: [
        [...]
        ValidationMsgService
    ],
    [...]
})
```

The (app-wide, but not the only) locales I load are taken from a barrel file reading:

**core/locales/index.ts**
```
//  Barrel file for translations
//  list all translated languages as exports...

export let AppDE = require('./locale-de.json');
export let AppEN = require('./locale-en.json');
```

Here comes the hard part:

- the locales include navigation menu entries etc. plus translations for the app-wide `ValidationMsgService` provided in `app.module.ts`.
- that `ValidationMsgService` basically takes any `FormGroup` object, parses its errors, maps them via interfaces and translates them accordingly. I use it for every form.
- with versions prior to the current `angular-l10n@4.0.0-beta.4` for my `angular v5.0.0-beta.7`, I was able to achieve something similar to the following:

**signup.module.ts (lazy-loaded)**
```
import { TranslationModule, TranslationService, L10nConfig, L10nLoader } from 'angular-l10n';

import { SignupEN, SignupDE } from './locales'; // again from a barrel, now with translations for the lazy module only

/**
 * Defines SignupModule's imports, declarations and providers.
 */
@NgModule({
    imports: [
        // LocalizationModule.forChild(l10nConfig), // New lazy instance of LocalizationService.
        SharedModule, // has CommonModule and ReactiveFormsModule
        TranslationModule.forChild(signupL10nConfig), // New lazy instance of TranslationService.
        SignupRoutingModule
    ],
    declarations: [
        SignupComponent
    ],
    providers: [
        SignupRoutingProviders,
        SignupService
    ]
})

/**
 * The SignupModule class is the module for mbs application's signup page.
 * The module is lazy loaded by {@link CoreRoutingModule}.
 */
export class SignupModule {
    /** Creates a new log catalog for SignupModule. */
    private log: any = Log.create('signup.module');
    /**
     * Creates and initializes the object created with the AppComponent class.
     *
     * @param {L10nLoader} l10nLoader L10nLoader from `angular-l10n`
     * @param {TranslationService} translation TranslationService from 'angular-l10n'
     */
    constructor(
        public l10nLoader: L10nLoader,
        public translation: TranslationService
    ) {
        this.l10nLoader.load();
        this.log.d('l10n', 'loaded ' + JSON.stringify(this.translation.getConfiguration()));
    }
}
```

The `SignupComponent` declared features a form which has its errors translated by `ValidationMsgService`. The benefit of this is (would be, to be precise) that during display of the translated error message, I could switch the language and the `translationChanged` event would trigger a re-translation of the error messages and update them on-the-fly.

Unfortunately, this does not work. `ValidationMsgService` looks up translation values and only finds those related to `signup.XYZ` instead of `app.XYZ`.

What I do not quite understand is that for my navigation menu entries (using app-wide locales) everything works finde, but for (`@Injectable()`) services used in lazy modules, it does not.

_Do you have a clue or hint?_  Is it a scope / zone topic?

**Expected behavior**
As in previous versions of this lib, new directly-loaded translation data for lazy-loaded modules should be added to existing directly-loaded translation data.

App-wide services (using non-lazy translation data) that are injected into lazy-loaded modules should still be able to use the non-lazy translation data.

**Specifications: Angular version, library version, environment, browser**
- `angular-l10n@4.0.0-beta.4`
- `@angular/core@5.0.0-beta.7`
- `Win10`
- `Chrome 61`

Thank you for any help or guiding examples (I could not find in the docs or sample app so far)!
Christian

**Comment by robisim74** [comment]
Hi Christian,

I have a question. You are using _direct loading_, but you load the translation through a request of json files: are you sure that the json files are bundled in your app and that you don't have http requests?
Direct loading needs that translations are immediately available.

If you are sure, you don't need to use:
- advanced initialization with APP_INITIALIZER (because you don't wait the loading of json files)
- caching: it works only with asynchronous loading
- _finally you don't need to use `forChild` method and a new configuration in lazy loaded modules: because the translations are immediately available, you can add all the translations in `AppModule`, and simply import `TranslationModule` (or `LocalizationModule`) without methods in lazy loaded modules_

However, you can keep your configuration, _but you need to explicitly re-add the translation files you need in your lazy loaded module_:  _when you use the _forChild_ method, you create a new instance of the `TranslationService` and its configuration, but your `ValidationMsgService` is unique for the whole application._ So when `ValidationMsgService` is injected from the lazy loaded module, it only sees the data of the new instance of the `TranslationService`. 

I think I understand why with the previous versions of the library you worked: the old configuration method created a new instance of a service for the configuration, and in the case of direct loading, saved the data, which was then copied into the `TranslationService`.
The new configuration, on the other hand, is just an interface, and data is added directly to the service, as in the case of asynchronous loading. The problem of redundancy is resolved with the caching mechanism. The library is lighter, faster and the mechanisms are now uniform. _So the fact that it worked before was just a case, a side effect not expected._

I think the two best solutions are these:

- Don't make translation directly into the `ValidationMsgService`: I also have apps that have shared services between lazy loaded modules: _but they only return the translation keys and then the translation is done directly in the components._

- Add all translation files to `AppModule`: _the library does not get any benefit from the `forChild `method because you are using direct loading_:

**app.module.ts**

```
const appL10nConfig: L10nConfig = {
    ...
    translation: {
        translationData: [
            { languageCode: 'de', data: AppDE },
            { languageCode: 'de', data: SignupDE },
            { languageCode: 'en', data: AppEN },
            { languageCode: 'en', data: SignupEN }
        ],
        composedKeySeparator: '.',
        missingKey: 'No translation key',
        missingValue: 'No translation value'
    }
};

@NgModule({
    imports: [
        [...]
        LocalizationModule.forRoot(appL10nConfig),
        [...]
    ],
    [...]
    providers: [
        [...]
        ValidationMsgService
    ],
    [...]
})
```

**signup.module.ts (lazy-loaded)**

```
@NgModule({
    imports: [
        LocalizationModule, // Put it here, or once in the SharedModule
        SharedModule,
        SignupRoutingModule
    ],
    ...
})

export class SignupModule { }
```

Let me know.

Greetings,
Roberto

**Comment by robisim74** [comment]
I'm closing this issue. Feel free to reopen it if you need. Greetings

**Comment by csentis** [comment]
Hi Roberto,

I must say I have been procrastinating answering you to your very concise, guiding and helping reply. Please excuse me not reverting earlier. It is (yet) a private project I pursue and I am still bound by work for a larger corporation.

First of all: I had used direct loading (per module) since I was assuming the localization data to be something that might need protection by being bundled (by webpack) into the module chunk. Protection as intellectual property. I now think this assumption was over the top. Your suggestions helped me realize that a central l10n json resource somewhere under `/assets` was the way to go.

Once I had undergone that comparably larger refactor - which was also a bit enriched by switching to an angular v5.0.0 RC, I felt that I had made much better use of the more intricate features of your fantastic lib - especially w.r.t. caching.

I have followed your advice and now use the core translation data in the `AppModule`, but repeat loading the core l10n json + the lazy l10n json in the lazy-loaded modules. `LocalizationModule` comes in via a `SharedModule` - it all works like a charm.

All in all, though late, I have to say: thank you very much for bothering to give such helpful feedback and guiding me into the right direction!
Christian
