### ISSUE TITLE
Availability of date/number/currency formatting in offline environment?

### ISSUE THREAD

**Issue by k-vekos** [robisim74/angular-l10n#141]
I understand that angular-l10n uses the [Intl API](https://developer.mozilla.org/it/docs/Web/JavaScript/Reference/Global_Objects/Intl) but I'm not understanding where the resources are stored for this Intl API. If a user is viewing my site without connection to the internet will their browser not be able to fetch Intl API resources from the internet or are these resources installed with the browser?

In the case that the resources *are* fetched from the internet is there a way to host these resources as part of my website instead and tell angular-l10n to fetch them from my server rather than online?

Thanks!

**Comment by robisim74** [comment]
Intl API is an object of the browsers, so it works also offline.

Try to visit the sample: https://robisim74.github.io/angular-l10n-sample/#/home

Then open the Console > Network and check _Offline_: try to change language: dates, numbers & currencies are translated (not texts, because it uses json files).

However, you can also add a local polyfill if you want.
