### ISSUE TITLE
Endless translation loop from double translation, browser locks up

### ISSUE THREAD

**Issue by AHelper** [robisim74/angular-l10n#155]
**I'm submitting a...**
```
[x] bug report
[x] feature request
[ ] support request
```

**Expected behavior**
Ideally, this shouldn't hit an infinite loop in the `MutationObserver` callback in `BaseDirective.addTextListener`.

**Actual behavior**
Browser will lock up in an infinite loop translating (would probably happen for all l10n directives, only tested with translating).

**Steps to reproduce the behavior**
Run https://plnkr.co/edit/FNpuWpDLdnp0vUQx8kJc
Notable parts of that plunker that make it fail:
- A l10nTranslate directive is put on `<some-external-shared-component>` in the App component. The intent was to only translate an attribute since the component.
- In the External component, `<p>` uses `[l10nTranslate]` - Not the same as just `l10nTranslate`
- In `src/main.ts`, use `enableProdMode()`

In non-prod mode, when `BaseDirective.ngAfterViewInit` uses `BFS.getTargetNode(this.element)` (for the l10nTranslate on `<some-external-shared-component>` in App), the regex in `BFS.SELECTOR` will match the `<p>` in External as angular gives the tag an `ng-reflect-l10n-translate` attribute to represent the `[l10nTranslate]` and excludes it from the search (trying to avoid an already translated node, :+1: ). In prod mode, those `ng-reflect-` tags are absent. If just `l10nTranslate` was used on `<p>`, it would still be on the element and gets filtered out correctly.  But instead, `BFS.getTargetNode(<some-external-shared-component>)` is returning `<p>`'s text node, which is already being translated, essentially resulting in a double translation of that text node.  And once one directive updates the translation, an endless loop of translation fighting commences.

This could result in a different way to detect if a particular node is being translated instead of relying on angular to set an attribute (like adding a flag on the node or something, this.element.angularL10nIsMutating=true). Or just a note in the docs saying, avoid getting into a situation where you end up double translating, use pipes if you don't want to accidentally translate more than you want else you can end up looping (maybe even a warning when this is detected to warn that things might break in prod mode?). Either way, it was an interesting dive figuring this one out :smile: 

**Specifications: Angular version, library version, environment, browser**
Angular 5.0.5, angular-l10n 4.1.2

**Comment by robisim74** [comment]
Hi Collin,

Thanks for the time you have dedicated to this analysis.

I think here we are in the presence of a development error. In the example, you are passing a parameter (`placeholder`) to a child component: therefore you should put the _translate_ directive in the child component:

```
@Component({
  selector: "some-external-shared-component",
  template: `<textarea [attr.placeholder]="placeholder" l10n-placeholder l10nTranslate></textarea><p [l10nTranslate]="{ name: name }">external.translation</p>`
})
export class External {
  @Input() placeholder: string;
  name = "World";
}
@Component({
  selector: 'my-app',
  template: `
      <some-external-shared-component placeholder="my-app.translation"></some-external-shared-component>
  `
})
export class App {
}
```

That works, because the _attribute placeholder_ is in the child component (`placeholder` in the parent is a parameter).

**Comment by robisim74** [comment]
I have done other tests, and everything works as expected (at least if we want to continue to guarantee the translation of nested elements and the dynamic change of the keys).

If I do this:

`<p l10n-title title="Greeting" l10nTranslate></p>`

it's wrong, but it works, because there aren't nested element (keep in mind that the `l10nTranslate` directive tries to find in any case the key to translate).

Also if I do this, it works:
```
<p l10n-title title="Greeting" l10nTranslate>
    <em l10nTranslate>Title</em>
</p>
```
because we have a duplicate translate directive, but the keys are immutables.

Also the following works:
```
<p l10n-title title="Greeting" l10nTranslate>
    Title
    <span [l10nTranslate]="{ user: username, NoMessages: messages.length }">User notifications</span>
</p>
```
because there is a key to translate for the first directive.

In your example you have:
```
<p l10n-title title="Greeting" l10nTranslate>
    <!-- no key  to translate !-->
    <span [l10nTranslate]="{ user: username, NoMessages: messages.length }">User notifications</span>
</p>
```
there isn't a key to translate, and the key for the second directive is dynamic: this generates the loop.

In the html syntax showed in the docs (https://robisim74.github.io/angular-l10n/spec/getting-the-translation/#directives), there is always an expression (key to translate), even when one wants to translate a single attribute.

**Comment by AHelper** [comment]
Yes, it's an error on my part.  In a sense, it isn't safe to put a directive on a component like that where, in this case, it was a component external coming from a separate package (although I control both :/) that had its own separate translations and as you said, it's trying to find _something_ to translate. Pipes in my case work as that's safe.

Consider the following, [it will also loop](https://plnkr.co/edit/TtDryarGPfiwJqw9RN31):
```html
<p l10n-title title="Greeting" l10nTranslate>
    <span [l10nTranslate]="{ user: username, NoMessages: messages.length }">User notifications</span>
    <span>Trailing</span>
</p>
```
If the order of those spans was flipped, it would be fine. 

Idea, what if `BaseDirective.setText` checked the key if the value changed first? That would avoid having a mutation event fire off.  It might not translate the right thing when these cases arise, but it won't lock up the browser (just confirmed locally):
```typescript
    protected setText(value: string): void {
        if (!!value && value !== this.key) {
            // ...
        }
    }
```
That wouldn't work if the translation result is also a valid translation input, but I think that can be ignored as there would be larger problems if your translations recurse like that :stuck_out_tongue:

**Comment by robisim74** [comment]
Yes, the correct way to translate a _parameter_ in an attribute of an extenal component is the pipe:

`<nested-component placeholder="{{ 'Greeting' | translate:lang }}"></nested-component>`

That is explained in the doc of directives: _You can't dynamically change expressions in attributes._

Then there is also the problem that the master key is missing (now I added also this warning to the docs):

```
<p l10n-title title="Greeting" l10nTranslate>
    <span [l10nTranslate]="{ user: username, NoMessages: messages.length }">User notifications</span>
    <span>Trailing</span>
</p>
```

Also the example above _loops_ because `<span>Trailing</span>` is another node, and the master key is always missing.

However, _this happens only when you use parameters_: `[l10nTranslate]="{ ... }"`. In this case the directive is removed by Angular as you noticed. You could solve in this way: 

```
<p l10n-title title="Greeting" l10nTranslate>
    <span l10nTranslate [l10nTranslate]="{ ... }">User notifications</span>
    <span>Trailing</span>
</p>
```

About a solution to avoid the loop:
1) The following avoids the loop, but the key won't be translated:
```
    protected setText(value: string): void {
        if (!!value && value !== this.key) {
            // ...
        }
    }
```

2) Add an attribute to all the (already) translated keys, something like: `l10nTranslated`.
This works, but all the translations then will have a double attribute... when only the case above `[l10nTranslate]="{ ... }"` needs the attribute.

So I think that the better solution would be:

`<span l10nTranslate [params]="{ ... }">User notifications</span>`

I could do this change without breaking changes (but changing the docs to encourage to use this syntax): what do you think?

**Comment by robisim74** [comment]
@AHelper I released a new version of the library, with the new suggested syntax for using parameters with directives: https://github.com/robisim74/angular-l10n/releases/tag/v4.1.3

Greetings

**Comment by AHelper** [comment]
@robisim74 Hey, took me a while to get back around to this.  Splitting that out would prevent the issue. :+1:
