### ISSUE TITLE
translate-method in .ts/.js classes does not work in IE

### ISSUE THREAD

**Issue by djb12** [robisim74/angular-l10n#16]
Hello,

I am developping an angular 2 (RC 5) application. As suggested, my components are inheriting from 'Locale' and I inject LocaleService and LocalizationService into them.

To localize strings inside .ts/.js-classes, I use 

`this.localization.translate('KEY_FOR_RESOURCE')`

In my bootstrap component, I add a reference to my json file

`this.locale.addLanguage('en');`
`this.locale.definePreferredLanguage('en', 5);`

and I use a translation provider

`this.localization.translationProvider('./resources/locale/locale-');`
`this.localization.updateTranslation();`

All works fine in Chrome but in Internet Explorer 11 and in Edge, the keys are displayed instead of the actual resources. So I don't see the actual string but 'KEY_FOR_RESOURCE' (the parameter for the translate method).

I suspect that the Components are created before the resource file has been loaded and the LocalizationService is not yet able to provide the translations. I tried to provide them from the construtor, in ngOnInit, ngAfterViewInit and ngAfterContentInit. Nothing works.

Any ideas? Since all works fine in Chrome, I suspect there is some kind of inconsistent behavior in the asynchronous loading of the translation files.

Accessing resources from HTML works fine in all browsers, it's only .ts/.js which causes problems.

**Comment by robisim74** [comment]
Hi,

the problem is not the browser, although it's possible that Chrome is so fast to complete the loading of the json file before uploading the application. The problem is you can not call the `translate` method before the http get request of the json file is completed.
If you want to get a translation into your component while loading the application, I have to change the `LocalizationService` class to emit an event when the translation changes, so that you can subscribe to the event in this way:

```
    this.localization.translationChanged.subscribe(

        // Generator or next.
        (value: boolean) => { console.log(this.localization.translate('KEY_FOR_RESOURCE')); }

    );
```

Tell me if this can be useful, and I'll implement the change.

**Comment by robisim74** [comment]
I added the commit to the `LocalizationService` class that allows you to subscribe to the event as explained above.
If you want to test it, you can do so:
- Uninstall this library from your application
- Download this repository
- Follow the instructions of the README file to build the library and install it in your application

If it solves your problem, I'll include the commit in the next version of the library.

**Comment by djb12** [comment]
Hello robisim74,

Your implementation works wonderfully. Thank you very much.

There are still problems, however, when developping for more than one browser since Chrome is so fast. The translationChanged event does not get triggered for components loaded at application start in Chrome while it does be triggered in the Microsoft browsers.

At the moment, I have to set the translations inline when my variables are initialized for Chrome:

`public title = this.localization.translate('TITLE_KEY');`

For other browsers, I have to set them again in the subscribe method:

 `this.localization.translationChanged.subscribe((value: boolean) => this.title = this.localization.translate('TITLE_KEY'));`

This is okay, I guess, but it leads a certain amount of code duplication when the translation method needs to be called inside .ts/.js.

Don't know a way to avoid that, however .

**Comment by robisim74** [comment]
Strange, I tested it and it works fine without initialize it. Can you post the code of your component? This evening I'll try it.

**Comment by robisim74** [comment]
Hi @djb12,

I confirm to you that in my test it's never necessary to initialize the values of translations for Chrome.

However, as regards the bootstrap component, you could solve definitively the problem by calling the `updateTranslation` method (which is responsible for the http request) at the end of the constructor:

```
@Component({
    selector: 'my-app',
    template: '<h1>{{ title }}</h1>'
})
export class AppComponent extends Locale {

    public title: string;

    constructor(public locale: LocaleService, public localization: LocalizationService) {
        super(null, localization);

        this.locale.addLanguage('en');
        this.locale.definePreferredLanguage('en', 5);
        this.localization.translationProvider('./resources/locale-');

        this.localization.translationChanged.subscribe(

            () => { this.title = this.localization.translate('TITLE'); }

        );

        this.localization.updateTranslation();
    }

}
```

Please note that in all the other components in an app where you have a router, you should still initialize variables with the translation, because these components are loaded only when they are required, and after the initial event , the new property `translationChanged` is only updated when the selected language changes.

**Comment by robisim74** [comment]
I released the new [version](https://github.com/robisim74/angular2localization/releases) of the library that includes the commit. [Here](https://github.com/robisim74/angular2localization/blob/gh-pages/app/app.component.ts) you can also find an example of the document title translation.
