### ISSUE TITLE
Unable to detect language while trying to use country or script codes

### ISSUE THREAD

**Issue by joshualeduc** [robisim74/angular-l10n#170]
**I'm submitting a...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Expected behavior**
Using a virtual machine with the operating system and chrome browser in the same language, I expect the angular-l10n plugin to request the correct matching language. I also expect composedLanguage to allow me to differentiate between traditional and simplified Chinese.

**Actual behavior**
2 character languages work correctly with the TranslationModule. But through various configurations I am unable to use country or script codes. I will either get a 404 error like `locale-zh-.json not found` or my app will not detect a language and only look for my `defaultLocale`.

In between every test I close and reopen google chrome. I then clear the cache and do a hard refresh.

**Steps to reproduce the behavior**

Config 1 using the `TranslationModule` - 2 character languages work here
~~~~
//SupportedLanguages is the same in all 4 configurations
const SupportedLanguages = [
	{ code: 'en', dir: 'ltr' },
	{ code: 'de', dir: 'ltr' },
	{ code: 'es', dir: 'ltr' },
	{ code: 'fr', dir: 'ltr' },
	{ code: 'it', dir: 'ltr' },
	{ code: 'ja', dir: 'ltr' },
	{ code: 'pt', dir: 'ltr' },
	{ code: 'ru', dir: 'ltr' },
	{ code: 'zh', dir: 'ltr' }
];

const l10nConfig: L10nConfig = {
  locale: {
    languages: SupportedLanguages,
    language: 'en',
    storage: StorageStrategy.Cookie
  },
  translation: {
    providers: [
      // out for testing { type: ProviderType.Fallback, prefix: './assets/lang/locale-en', fallbackLanguage: [] },
      { type: ProviderType.Static, prefix: './assets/lang/locale-' }
    ],
    caching: true,
    missingValue: 'No key'
  }
}
~~~~

Config 2 trying to use country codes with the `TranslationModule` - 404 with locale-language-.json error
~~~~
const l10nConfig: L10nConfig = {
  locale: {
    languages: SupportedLanguages,
    language: 'en',
    storage: StorageStrategy.Cookie
  },
  translation: {
    providers: [
      //out for testing { type: ProviderType.Fallback, prefix: './assets/lang/locale-en-US', fallbackLanguage: [] },
      { type: ProviderType.Static, prefix: './assets/lang/locale-' }
    ],
    composedLanguage: [ISOCode.Language, ISOCode.Country],
    caching: true,
    missingValue: 'No key'
  }
}
~~~~

Config 3 with `defaultLocale` and `TranslationModule` - `defaultLocale` used every time
~~~~
const l10nConfig: L10nConfig = {
  locale: {
    languages: SupportedLanguages,
    defaultLocale: { languageCode: 'en', countryCode: 'US' },
    storage: StorageStrategy.Cookie
  },
  translation: {
    providers: [
      //out for testing { type: ProviderType.Fallback, prefix: './assets/lang/locale-en-US', fallbackLanguage: [] },
      { type: ProviderType.Static, prefix: './assets/lang/locale-' }
    ],
    composedLanguage: [ISOCode.Language, ISOCode.Country],
    caching: true,
    missingValue: 'No key'
  }
}
~~~~

Config 4 using the LocalizationModule - `defaultLocale` used every time 
~~~~
const l10nConfig: L10nConfig = {
  locale: {
    languages: SupportedLanguages,
    defaultLocale: { languageCode: 'en', countryCode: 'US' },
    storage: StorageStrategy.Cookie
  },
  translation: {
    providers: [
      // out for testing { type: ProviderType.Fallback, prefix: './assets/lang/locale-en-US', fallbackLanguage: [] },
      { type: ProviderType.Static, prefix: './assets/lang/locale-' }
    ],
    composedLanguage: [ISOCode.Language, ISOCode.Country],
    caching: true,
    missingValue: 'No key'
  }
}
~~~~

I don't need dates or currencies, I just need either country or script codes to read with zh-CN/zh-TW or zh-Hans/zh-Hant files.

**Specifications: Angular version, library version, environment, browser**
Angular 5.2.4
Angular-l10n 4.1.4
Angular cli 1.6.8
Chrome 64

**Comment by robisim74** [comment]
Hi @joshualeduc,

about the configurations you are trying:

1. For only `language`, it is correct.
2. It's wrong: to work with `composedLanguage` you need to set `defaultLocale`, and not only the language.
3. It's correct.
4. It's correct.

If you don't need dates & numbers, you can use `TranslationModule`, but always you must use `defaultLocale` (also when you change language you have to use `setDefaultLocale`).

About the first loading of the app: browser language is detected only when you use `language`, and not `defaultLocale`: that's because not all browsers use `languageCode-countryCode`. When you work with `defaultLocale` as with composed language, the default locale set in the configuration or stored in the storage (after the first choise of the user) is used.

I hope I have answered your question.

**Comment by joshualeduc** [comment]
That helps a lot, thanks. I do have two follow up questions. So it looks like configuration 3 is the closest to what I want for my needs. I now understand your cascading fallback system better too. With your fallback example in the docs it looks for `language-country`, then `language`, then `locale-global`, which I now assume is for browsers that do not support `language-country`. Does this look for an exact match of the json file, meaning that I need two separate files for every language for maximum browser compatibility? (ie. `locale-language-country.json` and `locale-language.json`) Or will it look for any file containing `locale-language`?

With my config 3 example and adding in a fallback provider looking for just the `language`, it is now correctly identifying the language code on initialization. My problem is that I am still getting the `locale-language-.json` 404 error.  When I go into the chrome's dev tool and check the console, `navigator.language` gives me `"zh-CN"` and `navigator.languages` is giving me `["zh-CN", "zh"]`. This leads me to believe that `languageCode-coutryCode` is supported, are these variables what you check on app initiation? I haven't dug into your code much yet.

**Comment by robisim74** [comment]
_Fallback providers_ use a key if the corresponding key was not found in the main file: it is a technique of working with translation files. You do not have to use them if you do not need them.

`navigator.language` is used only if you use configuration 1, where you set `language: 'en'`. In the other configurations is not used, because as I said not all browsers return a `languageCode-countryCode`, and is used `defaultLocale: { languageCode: 'en', countryCode: 'US' }`.

About your `locale-language-.json 404 error`: if you are doing more tests, remember to clean the browser cache (cookies or the storage you are using), because the library tries to get the language or the default locale from the storage if it is set.

However, If you still have problems, try to provide a repro, and I'll give it a look.

**Comment by robisim74** [comment]
A recap:

config 1)

- library tries to get the `language` from the storage
- or library tries to get the `language` from the browser
- or library uses the `language` set in the configuration

config 3 & 4)
- library tries to get the `defaultLocale` from the storage
- or library uses the `defaultLocale` set in the configuration

**Comment by joshualeduc** [comment]
Oh okay, that recap made everything clear. If I want to use a `countryCode` file anywhere in my app, then I need to have a `defaultLocale` set either in my configuration or by the user's input which will get saved in storage. My mistake has been thinking that the library could get the `countryCode` from a modern/compatible browser at startup. 

So as of this writing, there's no way to specify between simplified and traditional Chinese characters without input for the user. I can work with that.

Thank you for all your help, I really do appreciate the time you took today for those quick responses.
