### ISSUE TITLE
Problem loading chinese languages localization for date and time

### ISSUE THREAD

**Issue by harika13** [robisim74/angular-l10n#175]
**I'm submitting a...**
```
[ ] bug report
[ ] feature request
[ *] support request
```
I have added languages for locale initilizaation like below.

this.locale.AddConfiguration()
      .AddLanguages(['en', 'fr', 'zh_CN', 'zh_HK', 'zh_TW']);
    this.locale.init();

I cannot have one zh.json file because there are 3 different types of chinese translation json files.
My translation json files are in 'languagecode_countrycode' or just 'languagecode' format.

I passed 'zh_HK' in this.locale.setCurrentLanguage('zh_HK');

The above implementation works fine with translation since i have those json files with those names mentioned so it loads.

But when i do date, time localization it gives me 'invalid lang tag' since date time format doesn't understand zh_HK.

For it I have renamed my json file names to 'zh-hant-CN', 'zh-hant-TW', 'zh-hant-HK' then my translation files loads as well as date, time returns locale based data(displays in chinese).

I am passing this.locale.setCurrentLanguage('zh-Hant-HK'); 

Is this implementation right?

**Specifications: Angular 2, library version 2.0.11, environment, browser-all**

**Comment by robisim74** [comment]
@harika13,

`zh_HK` or `zh-hant-CN` are _locales_, and not _languages_.

Please see this question: https://github.com/robisim74/angular-l10n/issues/115

You can find the docs for Angular v2 here: https://github.com/robisim74/angular-l10n/blob/angular_v2/doc/spec.md

Otherwise since version 4 for Angular v5, it is also supported `languageCode-scriptCode-countryCode`: https://robisim74.github.io/angular-l10n/spec/configuration/#using-a-composed-language

Greetings
