### ISSUE TITLE
Timeout Setting for the ProviderType.WebAPI

### ISSUE THREAD

**Issue by dsuwirya** [robisim74/angular-l10n#181]
Hello,

Would it be possible to add timeout value setting for ProviderType.WebAPI ?

Supposed that my translation providers stack is as follow:

translation: {
    providers: [
      { type: ProviderType.Fallback, prefix: './assets/i18n/locale-en', fallbackLanguage: [] },
      { type: ProviderType.WebAPI, path: 'https://www.myserver.com/i18n/' },
    ]}

The problem right now is that if for any reason that www.myserver.com is not reachable, it will take about 30s ( i.e. default browser timeout ) before it fallbacks.

Thank you.

**Comment by robisim74** [comment]
Hi  @dsuwirya,

I never tried, but if you can't set the timeout server side, I think there are two way:

1. Create an interceptor in your app: https://stackoverflow.com/questions/45938931/angular-httpclient-default-and-specific-request-timeout

2. Create a custom provider: https://robisim74.github.io/angular-l10n/spec/configuration/#using-a-custom-provider and add a timeout to the http request: https://stackoverflow.com/questions/36719116/how-to-timeout-angular2-http-request

Let me know if you find a solution in the second way, because I could also add a new option in the library.

Greetings

**Comment by dsuwirya** [comment]
Hi, 

Really appreciate the prompt response !

Yes, currently we managed to workaround it using the 2nd option you mentioned above, where we extend HttpTranslationProvider, then we provide our custom HttpClient where we have the opportunity to set the timeout:

`
import 'rxjs/add/operator/timeout';

@Injectable() class CustomHttpClient extends HttpClient {
     public get(url: string, options?: any): Observable<any> {
        return super.get(url, options).timeout(1000);
     }
}
 `

But it would be wonderful, if we can somehow pass this timeout parameter somewhere in the args, which you then take it and use it inside the getTranslation() when you call the http.get() ?

Thanks.

**Comment by robisim74** [comment]
Yes, it is interesting. I'll try to add this feature in next release (but it is planned for Angular v6).

Let you know.

**Comment by robisim74** [comment]
Closed in v5.2.0
