### ISSUE TITLE
Showing translation keys for brief seconds.

### ISSUE THREAD

**Issue by dsuwirya** [robisim74/angular-l10n#183]
Hi,

Supposed my translation provider stack looks like follow:

translation: {
providers: [
{ type: ProviderType.Fallback, prefix: './assets/i18n/locale-en.json' },
{ type: ProviderType.Fallback, prefix: './assets/i18n/locale-fr.json'},
{ type: ProviderType.Fallback, prefix: './assets/i18n/locale-fr-FR.json' },
{ type: ProviderType.WebAPI, path: 'https://www.myserver.com/i18n/en.json' },
{ type: ProviderType.WebAPI, path: 'https://www.myserver.com/i18n/fr.json' },
{ type: ProviderType.WebAPI, path: 'https://www.myserver.com/i18n/fr-FR.json' }
]}

and I'm using the directive in my html as follow:

<span l10nTranslate>app.appname</span>

and my json files will contain <key, value> mapping, e.g.

"app.appname": "My application"

and I configure and pre-load the l10n via APP_INITIALIZER.

However, if it takes time for remote json files to come down, I often see the application is loaded with the 'app.appname' key displayed for brief seconds, then replaced with the proper value afterwards.

Is there any way we can avoid this? Or at least, is there any way to make the transition from 'empty' to 'something' rather than from 'key' to 'something' like this?

Thanks.

**Comment by robisim74** [comment]
Uhm... it is weird that the keys are showed using APP_INITIALIZER: maybe because you are sending too long requests to a web api. See also this issue: https://github.com/robisim74/angular-l10n/issues/179 We should investigate. 

By default, the key is showed because an empty value destroys the rendering.

However, if APP_INITIALIZER won't work, you could add an `ngIf` to the container of your app: you could create an `isAppReady `property, and set it to true when the `translationChanged` is fired, and show a spinner during the loading.

**Comment by dsuwirya** [comment]
I've followed #179, but still seeing the same problem. I can see this problem for example when I cut internet access to AWS S3 bucket where I hosted the json files. While waiting that request to get timeout, the keys are displayed in the app.

**Comment by robisim74** [comment]
Unfortunately, without a repro, I can't help you to understand why APP_INITIALIZER is not working.

Try to exclude some feature, and see if it works:
- exclude web api providers
- exclude request timeout

If it won't work anyway, maybe there is a different problem in the app: on StackOverflow there are a lot of different situations: https://stackoverflow.com/search?q=angular+app_initializer

**Comment by robisim74** [comment]
Closed due to inactivity.
