### ISSUE TITLE
translate attribute without translating element?

### ISSUE THREAD

**Issue by TheShanMan** [robisim74/angular-l10n#191]
**I'm submitting a...**
```
[ x ] bug report
[ ] feature request
[ ] support request
```

**Expected behavior**
be able to translate an attribute without translating the element itself, perhaps by providing an alternative to the "translate" directive that tells angular-l10n only to look for attributes that need translation. also, it took me a while to realize that the "translate" attribute was required in this case so if a fix for this isn't available quickly, perhaps the docs could explicitly declare the requirement.

**Actual behavior**
in order to translate an attribute, you have to also include translate attribute, causing element itself to translate too

**Steps to reproduce the behavior**
<span l10n-title title="translateThis" translate>butNotThis</span>

StackBlitz Template: https://stackblitz.com/edit/angular-l10n

**Specifications: Angular version, library version, environment, browser**
Angular 5.2, l10n 4.1.5, windows 10, chrome

**Comment by robisim74** [comment]
In the syntax of directives, it is explicitly showed that the main directive must always be present: https://robisim74.github.io/angular-l10n/spec/getting-the-translation/#directives and also in the sample for the attributes: https://robisim74.github.io/angular-l10n/spec/getting-the-translation/#attributes

That's by design, and I don't see any bug.

If you need to translate only the attribute and not the element itself, you can use the translate pipe.

Greetings

**Comment by TheShanMan** [comment]
Those are both the same link. I know it shows the main directive there but it doesn't explicitly state that requirement. It could be clearer is my point. Generally speaking it doesn't matter because people want both translated but in my use case I wasted time trying to figure out why it wasn't translating. Adding the pipe approach to the attributes section could be a part of clarifying that. Thanks for that suggestion.

----- Reply message -----

**Comment by robisim74** [comment]
Sorry, I edited the second link. Yes, you can manage your situation (no translating nested text elements) in two ways:
- If you don't have nested text elements: `<p l10n-attr attr="Greeting" l10nTranslate></p>`
- Using pipe:  `<p attr="{{ 'Greeting' | translate:lang }}">[nested text elements]</p>` + `Language `decorator in the component class

That's because `l10n-attr` is a simple html data attrubute, and without `l10nTranslate` directive the translation can't work (parsing all the DOM is not among the objectives of this library).

**Comment by robisim74** [comment]
Closed due to inactivity.
