### ISSUE TITLE
Angular Material tooltip not being translated

### ISSUE THREAD

**Issue by mikelweb** [robisim74/angular-l10n#194]
**I'm submitting a...**
```
[ ] bug report
[ ] feature request
[x] support request
```

**Expected behavior**
Angular material tooltip being translated
**Actual behavior**
I don't get the tooltip translated, I see the "Dashboard.NewDoc".

**Steps to reproduce the behavior**
I'm using `l10n-matTooltip` since it is an html attribute
`<mat-icon class="new" l10n-matTooltip matTooltipPosition="above"  matTooltip="Dashboard.NewDoc">new_releases</mat-icon>`

**Specifications: Angular version, library version, environment, browser**
Angular 5.2.5
Angular Material 5.2.1
Angular-l10n 4.1.5

**Comment by robisim74** [comment]
The correct form for translating html attributes is the following (you have to add the `l10nTranslate `main directive):

`<mat-icon class="new" l10n-matTooltip matTooltipPosition="above" matTooltip="Dashboard.NewDoc" l10nTranslate>new_releases</mat-icon>`

But I think in this case it won't work anyway, because `matTooltip` is not an html attribute, but an Angular directive that after the rendering has different attributes.

So IMO you should use translate pipe:

`<mat-icon class="new" matTooltipPosition="above" matTooltip="{{ 'Dashboard.NewDoc' | translate: lang }}">new_releases</mat-icon>`

**Comment by mikelweb** [comment]
Thanks for the quick response. It worked, between single quotes
`<mat-icon class="new" matTooltipPosition="above" matTooltip="{{ 'Dashboard.NewDoc' | translate: lang }}">new_releases</mat-icon>`

**but it doesn't react to language changes, is it normal?** or does it need a new bootstrapping?

**Comment by robisim74** [comment]
Sorry, I edited the post adding single quotes.

To use the translate pipe, you must use `Language `decorator in your component class. Please see the docs: https://robisim74.github.io/angular-l10n/spec/getting-the-translation/#messages

Greetings

**Comment by mikelweb** [comment]
Great, it works!
Thanks!

**Comment by naralasrikanth** [comment]
-I was using the  "@jsverse/transloco": "^7.5.0" 
unable to translate the tool tip message to transloco

imported the transloco service in the ts file 
 [matTooltip]="t('GLOBAL.DIALOG.CLICK_TO_PREVIEW')"  --> this file in the HTML file
 
 getting the error like
 ctx_r6.t is not a function
    at OfflineTestListComponent_td_28_Template
