### ISSUE TITLE
Custom formats not working with date pipe after updating Angular v4 to v6

### ISSUE THREAD

**Issue by VMiracle** [robisim74/angular-l10n#202]
**I'm submitting a...**
```
[ ] bug report
[ ] feature request
[x] support request
```

Up until recently, I was using a previous version of angular-l10n (the one for Angular v4). In some components, I used the date pipe (localeDate) and everything worked as expected. I recently updated versions, and changed the pipe to the new one (l10nDate).

**Expected behavior**

Before the update, I used localeDate with custom date formats (i.e. 'MMM/d/y'). I was expecting to use custom date formats with the new pipe, l10nDate

**Actual behavior**

When using the l10nDate pipe, I can only use the 8 formats listed in the documentation. If I try to use a custom format, it defaults to mediumDate

**Steps to reproduce the behavior**

In case of using pipes, use something like this (defaults to mediumDate)

{{ today | l10nDate:defaultLocale:'MMM d, y'}}

In case of using directives, use something like this (also defaults to mediumDate)

<p format="MMM d, y" l10nDate>{{ today }}</p>

Stackblitz fork with example (actually just shows that custom formats won't work with this pipe): https://stackblitz.com/edit/angular-l10n-zeqhdm

**Specifications: Angular version, library version, environment, browser**

Angular: 6.1.4
Angular l10n: 
Browser: Chrome
Webpack: 4.9.2

My question is, are custom formats no longer supported or am I trying to them incorrectly?

**Comment by robisim74** [comment]
Until Angular v4, `localeDate ` offered a wrapper of the original pipes. From Angular v5, the Angular team introduced a breaking change: it gave up the Intl API to use CLDR data.

From Angular v5, this library uses IntlAPI directly, and as for the custom format it is necessary to pass an object as defined in the Intl AP: https://robisim74.github.io/angular-l10n/spec/getting-the-translation/#using-a-custom-format

Therefore your example will become:

```
@Component({
  selector: 'pipe-test',
  template: `
    <p>MMM d, y: {{ today | l10nDate:defaultLocale:options}}
  `
})
export class PipeTestComponent implements OnInit {
  @DefaultLocale() defaultLocale: string
  
  today: number;
  options: DateTimeOptions = { year: 'numeric', month: 'long', day: 'numeric' };

  ngOnInit(): void {
    this.today = new Date('1/1/2018').getTime();
  }
}
```
Note that in this way the order month, day, year is not relevant, because it is automatically localized.

To know all the breaking changes from Angular v5 see this release: https://github.com/robisim74/angular-l10n/releases/tag/v4.0.0

**Comment by robisim74** [comment]
Closed due to inactivity.
