### ISSUE TITLE
plural support using standard ICU message format compiler

### ISSUE THREAD

**Issue by sharathc10** [robisim74/angular-l10n#217]
**I'm submitting a...**
```
[ ] bug report
[ ] feature request
[x ] support request
```
Had asked this question on stackoverflow but there was no response hence I am putting it here

**Expected behavior**
I am testing pluralization support using your example with the i18nPluralPipe.  However, the pluralMap used by the pipe does not support the standard ICU message format which is as follows:

{count, plural, 0=....}

as shown here - http://userguide.icu-project.org/formatparse/messages

**Actual behavior**

The pluralization works:
 
(1)  if pluralMap is defined as follows:
'assignment': {
            '=0': 'assignment', '=1': 'assignment', 'other': 'assignments'
        }

OR
(2) if the template has the following:
<span i18n>{assignments, plural, =0 {{{'assignment' | translate:lang }}} =1 {{{'assignment' | translate:lang }}} other {{{'assignments' | translate:lang }}}}</span>

I would like to put the above pluralization rule in the json file as follows:

"assignment":  "{assignments, plural, =0 'assignment'  =1 'assignment'  other 'assignments'}"

This is to make it convenient for a translator to translate the rule across a single line instead of across multiple files.  Also, this is more in line with the ICU message format.

Question:  How can I get the translation to work with the above in the json file?  Thanks for your help

**Steps to reproduce the behavior**

See above
StackBlitz Template: https://stackblitz.com/edit/angular-l10n

**Specifications: Angular version, library version, environment, browser**

**Comment by robisim74** [comment]
Hi @sharathc10,

basic, this library does not support i18n pluralization. Through the _i18nPlural_ option(https://github.com/robisim74/angular-l10n-sample/blob/cbf1b9b8cfb4431add05450e9b1ff9aa909acc46/src/app/app.module.ts#L57), it only deals with translating the result obtained by official Angular `i18nPluralPipe` which otherwise uses only one _locale_:
```
2 messaggi
2 messages
٢ رسائل
```
as in the sample app: https://github.com/robisim74/angular-l10n-sample/blob/master/src/app/i18n/i18n.component.ts

As explained in official Angular docs (https://angular.io/api/common/I18nPluralPipe), the `pluralMap` is `an object that mimics the ICU format`. So a mapping like this:
```
messageMapping:
      {[k: string]: string} = {'=0': 'No messages.', '=1': 'One message.', 'other': '# messages.'};
}
```
i think it conforms to the ICU format.

I know that _angular-translate_ gave the possibility to insert the ICU format in the json files, but this library has nothing to do with that: it tries to fill in some shortcomings of official Angular i18n.

However, if you think you have a light solution to implement this feature, feel free to do a pr.

**Comment by sharathc10** [comment]
Thank you for your response.  My current workaround is to put the following in a separate plural-mapping.json file -
{"assignment": {
        "=0": "assignment",
        "=1": "assignment",
        "other": "assignments"
    }

and initialize the the pluralMapping variable and use it in the template as follows:

<p *ngIf="itemPluralMappingJson">{{assignments}}{{assignments | i18nPlural:itemPluralMappingJson['assignment'] | translate:lang}}</p>

**Comment by robisim74** [comment]
@sharathc10 Thanks for sharing your solution. However, the question is related to the framework and not to this library, which as I said does not implement the pluralization itself but only the translation.

Greetings

**Comment by sharathc10** [comment]
Yes - I understand - but you are using the framework's solution for pluralization and this solution still uses the pipe provided by angular-l10n which is not available in the framework

**Comment by robisim74** [comment]
Ok, but at this point what do you expect from this library?

As I said, giving up the pluralization by framework for implementing the parsing of the json files to find the ICU format is not planned for this library.

**Comment by robisim74** [comment]
I'm closing this issue. Feel free to reopen if you need. Greetings

**Comment by sharathc10** [comment]
OK - thanks!
