### ISSUE TITLE
protected member of Localization and Translation are missing

### ISSUE THREAD

**Issue by FabienDehopre** [robisim74/angular-l10n#225]
**I'm submitting a...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Expected behavior**
The `Localization` and `Translation` classes should export the `LocaleService` and `TranslationService` respectively just like in the previous version of the lib (6.x) or the change should have been documented in the breaking changes of the current version (7.x).

**Actual behavior**
The `Localization` and `Translation` classes don't export the `LocaleService` and `TranslationService` any more.

**Comment by robisim74** [comment]
You are right: I updated the changelog: https://github.com/robisim74/angular-l10n/releases/tag/v7.0.0

Explanation: I had to remove them, because the instances always referred to the root level: this could cause side effects in _lazy loaded_ module if you create new instances using _forChild_ method.

Thanks for reporting.

**Comment by FabienDehopre** [comment]
Ok. I wasn't sure the removal was expected or not. 
I'm closing the issue since it's an intedended removal and the changelog mentions it.
