### ISSUE TITLE
Missing TLD Support

### ISSUE THREAD

**Issue by SvenBudak** [robisim74/angular-l10n#242]
I just switched from ngx-translate to angular-l10n because the seo relevant features, but realized that there is no TLD support.

Explaining my Case:

I buyed `domain.de` and `domain.com`
When the `.de` domain is called i want to load `de` language.
And if `.com` is called i want to load `en` language.

I think many people do it like this, if they have the luck that the domains are available. Not at last because its also recommended by Google: https://support.google.com/webmasters/answer/182192?hl=en

Is there any support for this planed soon?

**Comment by robisim74** [comment]
Hi @SvenBudak,

currently the support for SEO adds _Subdirectories with gTLD_ as in the link you provided, because this library is designed for a SPA. If you have different domains, I think it would be more appropriate to use Angular's native i18n solution.

However, I think you could implement your own function to detect the domain and forcefully set the language when the app starts.

Some links to extract the domain:
https://stackoverflow.com/questions/36222845/how-to-get-domain-name-for-service-in-angular2
https://stackoverflow.com/questions/48060246/how-to-extract-the-tld-from-the-url-in-javascript

Greetings

**Comment by SvenBudak** [comment]
@robisim74 thanks for the fast reply! What do you personally think? Should I use several domains with different TLD? Or just domain.app/langSlug/? Do you think that makes any difference from SEO's technical point of view?

Because then would be an easy way:

`domain.app` as main domain
`domain.de` redirects to `domain.app/de/`
`domain.com` redirects to `domain.app/en/`

Sounds like a good solution, but is this really a good way?

**Comment by robisim74** [comment]
_Pros_ and _Cons_ are in the link you provided. But the important thing is a semantic URL.

Then, I think the difference for the SEO is the use of the Server Side Rendering.
