### ISSUE TITLE
l10nTranslate directive used for attribute translation also translate its child mat-icon, breaking the icon display

### ISSUE THREAD

**Issue by Chadys** [robisim74/angular-l10n#252]
**I'm submitting a...**
```
[X] bug report
[ ] feature request
[ ] support request
```
**Goal**
I want to set a translated `aria-label` on a button, since that button only contains an icon and no text.

**Expected behavior**
The `aria-label` content is translated. The text inside `mat-icon` shouldn't get translated since the l10nTranslate directive is put to its `<button/>` parent tag.

**Actual behavior**
The `aria-label` content is translated. The text inside mat-icon is also translated, the "No key" text is displayed inside the button instead of the icon.

**Workarounds**
Either add a translation that does nothing for every icon label you wish to use (meh), or use the pipe and not the directive to translate  only the `aria-label` attribute, but you'll need the `attr.aria-label` notation (meh).

**Steps to reproduce the behavior**
https://angular-l10n-9kaspr.stackblitz.io/

**Specifications: Angular version, library version, environment, browser**

Firefox 67.0
```
  "dependencies": {
    ...
    "@angular/core": "^7.2.15",
    "@angular/material": "^7.3.7",
    "angular-l10n": "^7.2.0",
    ...
  },
```

**Comment by robisim74** [comment]
Please, see https://github.com/robisim74/angular-l10n/issues/191

If you use `mat-icon` with the _ligatures_, the directive tries to translate it. Because there isn't in your case a main text to translate, you have two ways:
- Use the translate pipe (better performance)
- Instead of using _ligatures_ with `mat-icon` (`<mat-icon>edit</mat-icon>`), register the icon (https://material.angular.io/components/icon/overview):

```
      <button type="button" matSuffix mat-icon-button type="button" color="primary" aria-label="EditUsername" l10n-aria-label l10nTranslate>
        <mat-icon svgIcon="edit"></mat-icon>
      </button>
```

Greetings

**Comment by Chadys** [comment]
Thanks, closing this in favour of #191 then
