### ISSUE TITLE
Module translation with imported module

### ISSUE THREAD

**Issue by tjaz-brelih** [robisim74/angular-l10n#254]
**I'm submitting a...**
```
[ ] bug report
[ ] feature request
[x] support request
```

**Issue**
Suppose we have a core module, which contains "core" components, such as toolbar, sidenav, routing, etc.
It also has it's own angular l10n configurations and translation files.
This module is then imported into app module, which also has it's own translation files.

In this case core module translation does not work. It uses "app" translation files, which may or may not contain the necessary translations of terms.
I suspect the culprit of this problem lies in wrong configuration.

Example project on StackBlitz : https://stackblitz.com/edit/angular-l10n-rykk4w

Now I know, this "problem" has at least a couple of workarounds:
- Move core components to app module and provide the necessary translations there.
- Use app module translations for core module components.

But I would still like to know whether the original "setup" could work.

**Comment by robisim74** [comment]
@tjaz-brelih A _core module_ is only a module within _app module_: this library creates a new instance of the translation service only for lazy loaded modules (compare the docs: https://robisim74.github.io/angular-l10n/spec/lazy-loading/).

There is no need to create a new configuration in the _core module_: simply divide the translation files or variables and load them into the app module.

Furthermore you are reinitializing and using `app_initializer` in each module (not correct).

I'm closing this issue because there is no issue with this library, but only with the structure of the Angular app.

Greetings
