### ISSUE TITLE
@Language not working when declared in base class

### ISSUE THREAD

**Issue by Warwizza** [robisim74/angular-l10n#273]
Expected behavior
Language decorator property in the base class would get set and used by the class that extends it

Actual behavior
the Language decorator property has no value 

Steps to reproduce the behavior
Stackblitz: https://stackblitz.com/edit/angular-l10n-ug9bae
The Stackblitzis a fork of your Stackblitz with a slight alteration. I added a base class and extended the AppComponent with the base class. So the @Language lang property now comes from the base class. But as you can see in the console it has no value, so the 'Change country' text will not be translated when clicking  the 'Italia' button

Specifications: library version
angular-l10n: 8.1.2

**Comment by robisim74** [comment]
Hi @Warwizza,

inheritance does not work for decorators in Angular. If you want to use it, you can extend the `Translation` class and avoid the decorator: https://github.com/robisim74/angular-l10n/blob/angular_v8/docs/spec/getting-the-translation.md#extended-classes

From version v9, decorators will be removed from this library because they do not work with Ivy: https://github.com/robisim74/angular-l10n/issues/257

See also releases: https://github.com/robisim74/angular-l10n/releases/tag/v9.0.0-rc.0

**Comment by Warwizza** [comment]
Hi Roberto,

Thank you for your quick response. I refactored the code so my base class extends the Localization class (I also use dates). This works like a charm.
Thank you again.
