### ISSUE TITLE
SyntaxError with Webpack Build

### ISSUE THREAD

**Issue by nappynapster** [robisim74/angular-l10n#28]
Hello,

I get an error when i want to build my anuglar 2.1.0 project: 
`ERROR in app.js from UglifyJs`
`SyntaxError: Unexpected token: punc ({) [./~/angular2localization/angular2localization.js:2,0]`

I use the latest version of angular2localization 1.1.1
I build my project like it's described in the official angular2 guide ->  https://angular.io/docs/ts/latest/guide/webpack.html

**Comment by robisim74** [comment]
Hi,

try to see if this [question](http://stackoverflow.com/questions/38387544/angular-2-webpack-build-from-uglifyjs-syntaxerror-unexpected-token-punc) can be useful. Otherwise compare the configuration of the [sample app](https://github.com/robisim74/angular2localization/tree/gh-pages), also built with webpack.

**Comment by robisim74** [comment]
I tried to recreate the problem: the error occurs because evidently you're using wrong imports.

You have to use:
`import { ... } from 'angular2localization';`
not:
`import { ... } from 'angular2localization/angular2localization';`

Please, read the [documentation](https://github.com/robisim74/angular2localization/blob/master/doc/spec.md) to know how to use this library.

Greetings
