### ISSUE TITLE
Migration guide or migration schematics

### ISSUE THREAD

**Issue by DaSchTour** [robisim74/angular-l10n#281]
**Is your feature request related to a problem? Please describe.**
I have a larger application using angular-10n version 8 and would like to migrate to version 9. Just updating to version 9 creates a lot of compile errors and I have no idea where to start with the migration.

**Describe the solution you'd like**
A guide or schematics on how to switch to version 9

**Describe alternatives you've considered**
Doing l10n on my own

**Comment by kferstl** [comment]
what is the point in breaking this library completely every few month? This library is so fundamental, people reference it in there libraries etc and you guys break it in every possible way on each upgrade.  Do you guys add any value there or simply break the signatures for fun?

**Comment by robisim74** [comment]
@DaSchTour Please, see the warning on releases: https://github.com/robisim74/angular-l10n/releases/tag/v9.0.0

The angular-l10n v9 for Angular v9 is basically a new library.

@kferstl I don't know what you're referring to, this library has been stable for years (just be evolved, and changes are inevitable). After many years, and due to the incompatibility of some fundamental features with the Ivy engine, there were two alternatives: rewrite the library from scratch, or stop the project.

**Comment by DaSchTour** [comment]
@robisim74 yeah I have read the warning. But I thought there would be some guidance on how move to the new version. What is supposed to be replacement for what and so on. How to change directives, configurations and so on.
If it's a new library I'll possible just re-evaluate which library to use or just stick with v8 till it breaks.

**Comment by robisim74** [comment]
@DaSchTour The new README was done in a very simple and step-by-step way: the new configuration, pipes, directives etc. The only way to upgrade, therefore, is to follow the README one step at a time.

However, in the next few days I will try to make a migration document to warn about the most important differences.

**Comment by robisim74** [comment]
@DaSchTour I have added a short migration guide: https://github.com/robisim74/angular-l10n/blob/master/MIGRATION_GUIDE.md

Any contribution is always welcome.

Greetings
