### ISSUE TITLE
Validation and Parsing number is not working for locale French and Spanish

### ISSUE THREAD

**Issue by nethravikram** [robisim74/angular-l10n#287]
**Describe the bug**
I am using Angular 6 and angularl10n-5.2.0 version. LocaleValidation is not working for Spanish and French locale. Other locales are working. 

**To Reproduce**
1. Configure the anuglarl10n module as per doc.
2. app.html:
<input id="parsingNum" [digits]="digits" name="decimal"
		[(ngModel)]="decimal" l10nValidateNumber="1.0-2"  [formControl]="decimalControl">
3. In App.ts -  Import { DefaultLocale,
  Language,
  LocaleService,
  LocaleValidation,
  TranslationService} from 'angular-l10n'
4. Choosing the locale fr-Fr () or es-MX locale and set the current this.localeService.setCurrentLanguage(selectedLocaleId)
5. Pass the data from input. For fr-FR: 3 456 789,23 and es-MX: 3,456.78'
6. Parsed number is NaN. 
7. Format error is 'true' (decimalControl.hasError('format')) and formControl validility (decimalControl.valid)is 'false'

**Expected behavior**

**Screenshots**
<img width="1245" alt="image" src="https://user-images.githubusercontent.com/16252150/76091026-c1fc3380-5fe2-11ea-903c-bc22ddc7ff77.png">

<img width="1245" alt="image" src="https://user-images.githubusercontent.com/16252150/76091073-e0fac580-5fe2-11ea-9129-6b3facb0acbb.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by robisim74** [comment]
@nethravikram Without seeing the code, it's hard to understand what is happening.

From what you posted, I notice that you are using `this.localeService.setCurrentLanguage` instead of `this.locale.setDefaultLocale` to set the locale.

Here you can find the sample app for the previous version of the library: https://github.com/robisim74/angular-l10n-sample

Note that in the versions following the one you are using, some changes had been made to the locales that use the space as thousands separator: #261

**Comment by nethravikram** [comment]
I did used setDefaultLocale and I am still facing same issue. I saw that the issue is fixed in V8. But for using Angularl10nv8 version, we need to upgrade to Angular8. But I need to have solution for Angular6 only. Is it possible to get the solution for Angular6 version of Angularl10n 5.2.0?

**Comment by robisim74** [comment]
I'm not sure that the problem you're having can be solved by that fix. The locales `es` and `fr` should work. `es` in particular does not use space as thousands separator.

However, have you tried installing the next version and seeing if it works despite the warnings?

**Comment by nethravikram** [comment]
Ok . es locale does not work even in latest version you have mentioned. .
Please check.
https://stackblitz.com/edit/angular-l10n-8rtx3m

I found the simple uitility to parse the number which is working for all locales.
at https://stackoverflow.com/questions/11665884/how-can-i-parse-a-string-with-a-comma-thousand-separator-to-a-number. 


function parseNumber(value, locale = navigator.language) {
  const example = Intl.NumberFormat(locale).format('1.1');
  const cleanPattern = new RegExp(`[^-+0-9${ example.charAt( 1 ) }]`, 'g');
  const cleaned = value.replace(cleanPattern, '');
  const normalized = cleaned.replace(example.charAt(1), '.');

  return parseFloat(normalized);
}

const corpus = {
  '1.123': {
    expected: 1.123,
    locale: 'en-US'
  },
  '1,123': {
    expected: 1123,
    locale: 'en-US'
  },
  '2.123': {
    expected: 2123,
    locale: 'fr-FR'
  },
  '2,123': {
    expected: 2.123,
    locale: 'fr-FR'
  },
}


for (const candidate in corpus) {
  const {
    locale,
    expected
  } = corpus[candidate];
  const parsed = parseNumber(candidate, locale);

  console.log(`${ candidate } in ${ corpus[ candidate ].locale } == ${ expected }? ${ parsed === expected }`);
}

Let me know once you have fix for 'es', 'es-MX'  locale.

**Comment by robisim74** [comment]
@nethravikram You are right, the thousands separator is not working for `es`, due to the fact that internally a negative value is used as reference value which is not supported by Intl for `es`: https://github.com/robisim74/angular-l10n/blob/8d22a657295c9bd22ae4112af134cdebe7072cc6/src/services/locale-validation.ts#L123

Due to inconsistencies such as this from Intl, validation via Intl was removed from the latest version of the library, and therefore it will not be fixed.

You can use the validation by renouncing the thousands separator, or by implementing your own solution, as required in the latest version of the library.

**Comment by robisim74** [comment]
I am closing this issue for the above reason.
