### ISSUE TITLE
Missing 'ngOnInit' method

### ISSUE THREAD

**Issue by Neill83** [robisim74/angular-l10n#298]
Hi. We are using v8.1.2 and my question is...

Why do we always need to implement OnInit?

`public ngOnInit(){}`

Could you remove the warning?
We are also using AOT compilation and i don't think its needed...

Regards

**Comment by robisim74** [comment]
In version v8 of this library, the implementation of the `OnInit `method was necessary for decorators (e.g. `@Language`), otherwise with AoT enabled the change of language at runtime did not work without reloading: https://github.com/angular/angular/issues/16023

If the warning bothers you, use `LogLevel.Off` during configuration.
