### ISSUE TITLE
How to set default value when key is not present in translation file?

### ISSUE THREAD

**Issue by tsukasa521** [robisim74/angular-l10n#31]
Hi,
I'm using Angular 2.0.0,

My problem is how to set default value when key is not present in translation file, it means the friendly value (eg. "No Key in DB") can be shown if the key not found.

Thanks.

**Comment by robisim74** [comment]
Hi,

at the moment, if the value of the translation is not present, the same key is returned (#1).

I think we have to define a strategy. If you need to handle missing keys:
- for development
- for production

In development, we could set a property to display a _friendly value_, or logging in console missing keys.
For production? I think we need to show or the same key, or an empty field.

What do you think about it?

**Comment by tsukasa521** [comment]
Agree with you. In my project, customer require display "No Key in DB" if no key found for production, because of they want to know which key don't config in resource file in the first time.

**Comment by robisim74** [comment]
At this point, I plan to add a property to set or with the same key or with a message, and I will let to the developer the responsibility to change it depending on the environment.

**Comment by robisim74** [comment]
Hi,

I added a commit that should solve your problem.

By default, if a key is not present in the `json`, the same key is returned.

When you initialize the `LocalizationService`, you can set a friendly value to use for these keys:

``` TypeScript
localization.translationProvider('./resources/locale-');
localization.setMissingValue("No key");
```

Alternatively, you can set a key to use for the missing keys, so that even this is translated:

``` TypeScript
localization.translationProvider('./resources/locale-');
localization.setMissingKey("MISSING");
```

and in the `json`:

```
{
    "MISSING": "No key",
    ...
}
```

If you want to test it, follow the instruction to build the library in the README.

This week I should release the new version of the library, along with the next version of Angular.

Let me know.

Greetings

**Comment by tsukasa521** [comment]
Many thanks, it's big help for me.

**Comment by robisim74** [comment]
Hi,

I released the new version that implements this feature.

Greetings

**Comment by tsukasa521** [comment]
Sorry reply later, work fine for new version, thanks for your support.
