### ISSUE TITLE
locale.language is empty, Error: angular-l10n (L10nDefaultTranslationLoader): Asset not found

### ISSUE THREAD

**Issue by bhaynes777** [robisim74/angular-l10n#336]
I am trying to get angular-l10n v.13.1.0 working in an Angular 13 project.

In my component, the injected L10nLocale has language set to an empty string.  I added subscribe calls to an injected L10nTranslationService as suggested here: https://github.com/robisim74/angular-l10n/issues/321#issuecomment-758926804 and got this error: "Error: angular-l10n (L10nDefaultTranslationLoader): Asset not found" 

My l10n-config looks like this:

```
import { L10nConfig } from "angular-l10n";

const i18nAsset = {
  'en-US': {
    "test": "Driver"
  },
};

export const l10nConfig: L10nConfig = {
  format: 'language-region',
  providers: [
      { name: 'app', asset: i18nAsset, options: { version: '13.0.0' } }
  ],
  fallback: true,
  cache: true,
  keySeparator: '.',
  defaultLocale: { language: 'en-US', currency: 'USD' },
  schema: [
      { locale: { language: 'en-US', currency: 'USD', units: { 'length': 'mile' } }, dir: 'ltr', text: 'United States' }
  ],
  defaultRouting: true
};
```

**Comment by robisim74** [comment]
Hi @bhaynes777,

i think the problem here is `fallback: true`: are you handle it by also providing translations that are country independent?

When fallback is enabled, and you have as format `language-region`, it tries to get also `language `data, and not only `language-region` data.

See here: https://github.com/robisim74/angular-l10n#translation-fallback

In any case the library uses the default locale if a locale is not included in your `schema`, even without enabling fallback.

**Comment by bhaynes777** [comment]
Thanks @robisim74 , setting fallback to false fixed the issue.
