### ISSUE TITLE
Translation from Object/Function

### ISSUE THREAD

**Issue by meriturva** [robisim74/angular-l10n#43]
As already asked to `ng2-translate` project 

https://github.com/ocombe/ng2-translate/issues/124

i just would like to know if your library could support translation calling object methods.
So thanks.

**Comment by robisim74** [comment]
Sorry, but it doesn't support functions for translations.

**Comment by meriturva** [comment]
Thanks @robisim74 Do you think is it possible to implement a special `LocalizationService` and inject on your package? i don't link so much to fork your project i just would like to extend it. Secondly....do you think pipe will remain "pure" with a method call instead string?

**Comment by robisim74** [comment]
Hi @meriturva,

_pipe_ is not a problem, because its input parameters are the key and the language, and not the function.

The points to be solved are two:
- the `translate` method of the `LocalizationService`
- how to load the js files

Regarding the `translate` method, I can add something like this:

```
public translate(key: string, args?: any, lang: string = this.languageCode): string {
...
        } else if (typeof value == 'function') { // Line 193

            var params = Object.keys(args).map((key) => {
                return args[key];
            });
            return value(...params);

        }
...
}
```

Regarding the second point, you can use the _Direct loading_ to load all the translations files before call the `updateTranslation` method, as explained here: https://github.com/robisim74/angular2localization/blob/master/doc/spec.md#3.2.1

I tested this solution: it works.

**Comment by meriturva** [comment]
So thanks @robisim74 i will try as soon as possible and keep you informed!

**Comment by atmanikumar** [comment]
Hi I'm Mani
I'm trying to translate in the component class 

//My component ts file

import { Translation, TranslationService } from 'angular-l10n';

text :String=this.translation.translate('Title');

 constructor(public translation: TranslationService) {
    super(translation)
console.log(this.text)//should print "Angular localization" but printing as "Title"
}

//My literal json
{
    "Title": "Angular localization"
}

Please Help me

thisIt

**Comment by robisim74** [comment]
@manikumaar This is a different issue. However, please see the documentation: https://github.com/robisim74/angular-l10n/blob/master/doc/spec.md#3.3. When you try to get the translation at the time that the component is loaded (in the constructor), you have to also subscribe to event. If you need, please open a new issue. Greetings

**Comment by robisim74** [comment]
Hi @meriturva, I'm closing this issue. If you'll still need this feature, reopen it. Greetings
