### ISSUE TITLE
Can't load an additional Provider during the runtime

### ISSUE THREAD

**Issue by TimWieder** [robisim74/angular-l10n#67]
We have the issue that we want to add an additional provider during the runtime. The problem is that the provider we add isn't loaded in the "translationData"-object without a language switch. A function to update the translationData without changing the language would be nice.

**Comment by robisim74** [comment]
It's not possible adding a provider a runtime without changing the language for two reasons:
- _pure pipes_ need that the _key_ or _lang_ parameter changes to update their values
- the time for the http request would cause a delay in updating the _directives_ and the values would not even readily available in classes

**Comment by robisim74** [comment]
Another option is lazy loading: https://github.com/robisim74/angular-l10n/blob/master/doc/spec.md#5

**Comment by Neill83** [comment]
@robisim74 is it possible to have more than one provider running in one component?

Example:

I add one "main"-Provider in my mainComponent. Then I need another provider in a second component with more translations. Those translations are only needed in the second component.

So is it possible to use both provider in the second component?

regards

**Comment by robisim74** [comment]
Sincerely, guys, I don't understand that problem: not all values are used by all components: you can add all the translation providers you want when configuring them: the translation service will find the values that the various components need:

```
this.translation.addConfiguration()
    .addProvider('./assets/locale-')
    .addProvider('./assets/global-')
    ...
```

Another thing is lazy loading: it doesn't load the data of other modules during the application's boostrap, so you can include the components that have their translation files as explained here: https://github.com/robisim74/angular-l10n/blob/master/doc/spec.md#5

**Comment by Neill83** [comment]
this works. But what does **not** work is this:

1. in my mainComponent
`this.translation.addConfiguration().addProvider('src/app/assets/lang/locale_');`

2. then follow this [Guide](https://github.com/robisim74/angular-l10n/blob/master/doc/spec.md#5)

3. implement
 ```
constructor(public translation:TranslationService)
    {
        this.translation.addConfiguration().addProvider('src/app/assets/lang/whatever/whatever_');
        this.translation.init();
        
        alert(this.translation.translate('test'))
    }
```

result is an alert with key as text and not the text from the json.

I debugged it and the provider is correctly added to the config but no "test"-key is in the translationData object.

**Comment by robisim74** [comment]
Is that component included in a lazy loaded module? Are you providing `TranslationModule.forChild() `or `TranslationService` as a provider in your component? You need to create a new instance of the service in another module, otherwise the first instance of the service always wins : https://angular.io/docs/ts/latest/cookbook/ngmodule-faq.html#!#q-module-provider-duplicates

Here you can find an example:
https://github.com/robisim74/angular-l10n-sample/blob/master/app/app.routes.ts#L13
https://github.com/robisim74/angular-l10n-sample/blob/master/app/list.module.ts
https://github.com/robisim74/angular-l10n-sample/blob/master/app/list.component.ts#L35-L38

_ListModule_ is lazy loaded, and creates a new instance of `TranslationService`, so the _ListComponent_ can use different and shared translation files.

However your alert can't work: you are asking for a translation before the http request is completed. See here: https://github.com/robisim74/angular-l10n/blob/master/doc/spec.md#3.4

If you need, please open a new issue.
