### ISSUE TITLE
Directive translation issue when variable is not initialise.

### ISSUE THREAD

**Issue by skyfremen** [robisim74/angular-l10n#71]
I am trying to use directive to localise my date and numbers. I notice that if I did not initialise the variable the directive will stop working. This is a problem to me because my date is retrieve from the database using observerables and will not be initialise at first when the page loads

This is a sample I used to reproduce the issue.
HTML
{{testDate}}
{{testNumber}}
{{testDate2}} // not working
{{testNumber2}} // not working

TS
private testDate: Date = new Date();
private testNumber: number = 1000;
private testDate2: Date; // Not initialise
private testNumber2: number; // Not initialise

ngOnInit() {
setInterval(() => {
this.testIncrement = this.testIncrement + 1;
this.testDate = new Date();
this.testDate2 = new Date();
this.testNumber = 1000 + this.testIncrement;
this.testNumber2 = 1000 + this.testIncrement;
}, 1000);
}

**Comment by robisim74** [comment]
Directive works on the DOM: it stores the first text that it finds when it is rendered, and listens for changes (only from _angular-l10n v2.0.6_ ). It doesn't know anything about your subscription.
You have two way if you don't have an initial value:
- using a pipe instead of a directive
- using `*ngIf` , for example:
`<span *ngIf="!!today" localeDate>{{ today }}</span>`

**Comment by mscudlik** [comment]
another option is to use the changedetectorref as explained in the official documentation:
https://angular.io/docs/ts/latest/api/core/index/ChangeDetectorRef-class.html

though its probably better and easier to use the ngIf or pipe approach
