### ISSUE TITLE
Prefix the translate directive selector

### ISSUE THREAD

**Issue by IEvangelist** [robisim74/angular-l10n#81]
# Proposal
I have been a happy consumer of this library and appreciate all the efforts that have gone into making this so easy to consume, and for that I thank all the contributors! 

I wanted to propose a change in something that I recently stumbled upon. The `translate.directive.ts` directive has a selector of `[translate]`. However, there is an HTML global translate element attribute that already exists - detailed on [w3schools](https://www.w3schools.com/tags/att_global_translate.asp) and [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/translate). As such, I'm proposing that the `translate` directive selector be prefixed as follows (in accordance with the [recommended best practice](https://github.com/angular/angular/issues/1598)):
```
@Directive({
    selector: '[l10n-translate]'
})
```
## Breaking change
Anyone currently using the directive as follows will be affected:
```
<span translate>Key</span>
```
They would have to update their consumption of this directive in their markup as follows:
```
<span l10n-translate>Key</span>
```
## Additional consideration
It might be a valid consideration to prefix all directives and components with `l10n` to more easily identify them, isolate them more explicitly and be consistent with this proposed change.

**Comment by robisim74** [comment]
Hi @IEvangelist,

thanks a lot for this topic. I was not sure to use `l10n-translate` as selector for _translate_ directive, because as we can see in the links that you have provided, it's an experimental feature, and for now browsers don't support it.

However, we can introduce this change, and without breacking changes: simply, we can mantain a double selector:

```
@Directive({
    selector: '[translate],[l10n-translate]'
})
```
and adding another `@Input` parameter.

That way, anyone who wants to get ready for the new feature will be free to do so, while others will not have to change anything. We could include this feature in the next minor version.

What do you think?

**Comment by IEvangelist** [comment]
Hi @robisim74,

I like that idea... I think it is a great compromise. Thank you for your quick response.

**Comment by robisim74** [comment]
With the latest version 3.1.0, you can use also `l10nTranslate` as selector.

**Comment by robisim74** [comment]
All the directives, now also have the `l10n` prefix: https://github.com/robisim74/angular-l10n/blob/master/doc/spec.md#3.2 without breaking changes.

Greetings
