### ISSUE TITLE
Consider Providing Mocks for LocaleService and Localization Service

### ISSUE THREAD

**Issue by on3al** [robisim74/angular-l10n#85]
Having components that use the localization services become difficult to test due to the number of dependencies introduced. It would be extremely useful if you could provide Mock services (or an interface) for the services that could be used in unit test.

**Comment by robisim74** [comment]
Did you see here? https://github.com/robisim74/angular-l10n/blob/master/integration-tests/pipes/translate.pipe.spec.ts#L86 I use a MockBackend to provide data. And here: https://github.com/robisim74/angular-l10n-sample/blob/master/tests/home.component.spec.ts I use the real services. Maybe they can help you in the meantime.

About Mock services: I think it's not possible to create fake default services because the data you entered will hardly be able to test all applications.

About the interfaces, they are missing in this project, so I think I will add them as soon as possible.

But I still wonder whether they are actually usable for service testing: http://stackoverflow.com/questions/42492017/using-angular2-testbed-to-mock-a-service-with-a-non-concrete-class-interface-par

Can you help me by providing some examples? So that I can decide what is the best way to go.

Thanks!

**Comment by robisim74** [comment]
Interfaces have been added in the latest version 3.1.0.

**Comment by on3al** [comment]
Thank you. Having the interfaces allows me to create mocks in the manner I expected.
